// Code generated by goctl. DO NOT EDIT.
package types

type Address struct {
	Address string `form:"address"`
}

type UserReq struct {
	UserName  string        `json:"username"`
	Address   string        `json:"address"`
	Email     string        `json:"email"`
	Twitter   string        `json:"twitter"`
	Avatar    string        `json:"avatar"`
	Bio       string        `json:"bio"`
	Banner    string        `json:"banner"`
	Signature SignatureData `json:"signature"`
}

type UserResp struct {
	UserName  string `json:"username"`
	Address   string `json:"address"`
	Email     string `json:"email"`
	Twitter   string `json:"twitter"`
	Avatar    string `json:"avatar"`
	Bio       string `json:"bio"`
	Banner    string `json:"banner"`
	Timestamp int64  `json:"timestamp"`
}

type SignatureData struct {
	Message   string `json:"message"`
	PublicKey string `json:"publicKey"`
	Salt      string `json:"salt"`
	Data      string `json:"data"`
}

type Response struct {
	Message string `json:"message"`
}

type FilePath struct {
	Path string `form:"path"`
}

type FileResponse struct {
	Code []byte `json:"code"`
}
