version: "3.3"
services:
  megaoasis_profie:
    build:
      context: "./"
      args:
        RT: ${RUNTIME}
    ports:
      - "8888:8888"
    networks:
      - network
    restart: always
    container_name: megaoasis_profie_${RUNTIME}
    volumes:
      - ./logs:/go/application/Logs/
      - /home/ubuntu/img:/go/application/img
    depends_on:
      - redis

  megaoasis_email:
    build:
      context: "./mega-email"
      args:
        RT: ${RUNTIME}
    ports:
      - "3333:3333"
    networks:
      - network
    restart: always
    container_name: megaoasis_email_${RUNTIME}
    volumes:
      - ./logs_ws:/go/application/Logs/
    depends_on:
      - redis

  megaoasis_img:
    build:
      context: "./img"
      args:
        RT: ${RUNTIME}
    ports:
      - "8090:8090"
    networks:
      - network
    restart: always
    container_name: megaoasis_img_${RUNTIME}
    volumes:
      - ./logs_ws:/go/application/Logs
      - /home/ubuntu/img:/go/application/img

  redis:
    image: redis
    networks:
      - network
    restart: always
    ports:
      - "6379:6379"
    container_name: megaoasis_cache_${RUNTIME}


