// Code generated by goctl. DO NOT EDIT.
package types

type Address struct {
	Address string `form:"address"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UserResp struct {
	UserName      string `json:"username"`
	Address       string `json:"address"`
	Email         string `json:"email"`
	Twitter       string `json:"twitter"`
	Avatar        string `json:"avatar"`
	Bio           string `json:"bio"`
	Banner        string `json:"banner"`
	Timestamp     int64  `json:"timestamp"`
	TtitterUpdate int64  `json:"twitterupdate"`
	EmailUpdate   int64  `json:"emailupdate"`
}
